name: Build and Test Branda-Server Project

on:
  push:
    branches: [main, develop, develop, testing]
  pull_request:
    branches: [main, staging, develop, testing]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x # Adjust to your desired Node.js version
      - name: Install dependencies
        run: npm install
      - name: Run e2e tests
        run: npm run test:e2e
      - name: Build the project
        run: npm run build